# -*- coding: utf-8 -*-
"""Gio Filio — Datos de zonas de Ciudad de México.
Las 16 alcaldías oficiales + colonias prioritarias.
TODO el contenido de este archivo pertenece exclusivamente a la Ciudad de México.
"""

MARCA = {
    "nombre": "Gio Filio",
    "descriptor": "Tu espacio ideal",
    "rol": "Asesora Inmobiliaria",
    "ciudad": "Ciudad de México",
    "dominio": "https://giofilio.com",
    "email": "hola@giofilio.com",
    "whatsapp": "525512345678",
    "whatsapp_display": "+52 55 1234 5678",
    "instagram": "https://instagram.com/gio.filio",
    "facebook": "https://facebook.com/giofilio",
    "linkedin": "https://linkedin.com/in/giofilio",
}

# ---------------------------------------------------------------- alcaldías
# clave: slug ; nombre ; lat, lng ; perfil editorial
ALCALDIAS = [
    {
        "slug": "alvaro-obregon", "nombre": "Álvaro Obregón", "lat": 19.3595, "lng": -99.2033,
        "resumen": "Del empedrado de San Ángel a las torres de Santa Fe. Es la alcaldía con mayor contraste de la ciudad: casonas con historia, corredores corporativos y zonas residenciales arboladas.",
        "perfil": "Álvaro Obregón concentra tres realidades inmobiliarias distintas. San Ángel y Chimalistac conservan casas de piedra volcánica, calles empedradas y una vida de barrio que se defiende sola. Jardines del Pedregal ofrece terrenos amplios y arquitectura moderna mexicana sobre roca volcánica. Y hacia el poniente, Santa Fe funciona con una lógica vertical y corporativa. Comprar aquí exige entender bien en cuál de las tres estás.",
        "vive": "Se vive con auto en la mayor parte de la alcaldía, aunque San Ángel y Chimalistac permiten resolver mucho caminando. Los fines de semana giran alrededor del Bazar del Sábado, los mercados de Altavista y la oferta gastronómica sobre Avenida de la Paz.",
        "destacados": ["San Ángel", "Jardines del Pedregal", "Chimalistac", "Guadalupe Inn", "Florida"],
    },
    {
        "slug": "azcapotzalco", "nombre": "Azcapotzalco", "lat": 19.4844, "lng": -99.1844,
        "resumen": "Una alcaldía de vocación industrial que se está reconvirtiendo. Precio por metro cuadrado accesible y desarrollos verticales nuevos sobre los corredores principales.",
        "perfil": "Azcapotzalco es de las zonas donde el precio por metro cuadrado todavía permite entrar al mercado de compra sin un enganche desproporcionado. La reconversión de antiguos terrenos industriales ha traído desarrollos verticales con amenidades sobre Camarones y Ferrocarriles Nacionales. Es una apuesta de mediano plazo más que una compra de estilo de vida inmediato.",
        "vive": "Buena conexión con Línea 6 y Línea 7 del Metro, y acceso directo al Circuito Interior. La vida de barrio se concentra en el centro histórico de Azcapotzalco y su parque Tezozómoc.",
        "destacados": ["Centro de Azcapotzalco", "Clavería", "Nueva Santa María", "El Rosario"],
    },
    {
        "slug": "benito-juarez", "nombre": "Benito Juárez", "lat": 19.3861, "lng": -99.1653,
        "resumen": "La alcaldía más equilibrada de la ciudad para vivienda vertical: servicios completos, Metro en casi cualquier punto y una relación precio-calidad difícil de igualar.",
        "perfil": "Si tuviera que recomendar una sola alcaldía a alguien que compra su primer departamento en la ciudad, empezaría por Benito Juárez. Del Valle, Narvarte, Nápoles y Portales tienen infraestructura resuelta, mercados públicos vivos, escuelas y hospitales cerca, y una oferta de departamentos de 70 a 160 m² que rara vez se queda sin demanda. La plusvalía aquí es constante, no espectacular.",
        "vive": "Es la alcaldía con mayor densidad de estaciones de Metro y Metrobús. Se puede vivir sin auto en Del Valle o Narvarte con relativa facilidad. Parque Hundido, Parque de los Venados y el Parque Tlacoquemécatl marcan el ritmo de los fines de semana.",
        "destacados": ["Del Valle", "Narvarte", "Nápoles", "Portales", "Insurgentes Mixcoac", "Acacias"],
    },
    {
        "slug": "coyoacan", "nombre": "Coyoacán", "lat": 19.3467, "lng": -99.1617,
        "resumen": "Barrio con identidad propia. Casas con jardín, vida cultural constante y una demanda que no depende de las modas del mercado.",
        "perfil": "Coyoacán tiene un tipo de comprador muy claro: alguien que busca casa, jardín y silencio, sin salirse de la ciudad. El centro histórico de Coyoacán y Villa Coyoacán mantienen casonas de los años cuarenta y cincuenta que se venden por metros de terreno más que por metros de construcción. Hacia el sur, Copilco y Ciudad Universitaria imprimen un perfil más joven y de renta.",
        "vive": "Fines de semana de plaza, mercado de artesanías y librerías. Los Viveros de Coyoacán son el pulmón cotidiano de la zona. Movilidad principalmente en auto, con Línea 3 del Metro y Metrobús sobre Insurgentes.",
        "destacados": ["Villa Coyoacán", "Del Carmen", "Santa Catarina", "Copilco", "Romero de Terreros"],
    },
    {
        "slug": "cuajimalpa-de-morelos", "nombre": "Cuajimalpa de Morelos", "lat": 19.3573, "lng": -99.2986,
        "resumen": "Santa Fe, bosque y altura. La alcaldía con la vivienda vertical más nueva de la ciudad y las mejores vistas del poniente.",
        "perfil": "Cuajimalpa es donde la ciudad se vuelve vertical y contemporánea. Santa Fe concentra torres con amenidades completas, seguridad 24/7 y departamentos que salen al mercado con acabados de entrega inmediata. Hacia el bosque, Contadero y El Yaqui ofrecen casas en condominio con más terreno y clima notablemente más fresco. Es una zona que funciona muy bien para quien trabaja en el corredor corporativo del poniente.",
        "vive": "Movilidad dependiente del auto, aunque el corredor Santa Fe tiene transporte concesionado y acceso directo a la salida poniente de la ciudad. Centros comerciales, universidades privadas y oferta gastronómica dentro de las mismas torres.",
        "destacados": ["Santa Fe", "Contadero", "El Yaqui", "Bosques de las Lomas", "Lomas de Vista Hermosa"],
    },
    {
        "slug": "cuauhtemoc", "nombre": "Cuauhtémoc", "lat": 19.4326, "lng": -99.1533,
        "resumen": "El corazón de la ciudad. Roma, Condesa y Juárez concentran la mayor demanda de renta y la vida urbana más caminable de México.",
        "perfil": "Cuauhtémoc es donde la ciudad sucede. Roma Norte, Condesa e Hipódromo tienen edificios art déco protegidos, arbolado maduro y una densidad de restaurantes, galerías y cafés que no existe en ninguna otra parte del país. Es la zona con mayor rotación de renta y, por lo mismo, donde una propiedad bien ubicada casi nunca se queda vacía. También es donde hay que revisar con más cuidado antigüedad, estructura y régimen de condominio.",
        "vive": "Es la alcaldía más caminable de la ciudad. Metro, Metrobús, Ecobici y calles arboladas hacen que muchos residentes no usen auto entre semana. Parque México, Parque España y la Alameda ordenan la vida al aire libre.",
        "destacados": ["Roma Norte", "Roma Sur", "Condesa", "Hipódromo Condesa", "Juárez", "Cuauhtémoc", "Santa María la Ribera"],
    },
    {
        "slug": "gustavo-a-madero", "nombre": "Gustavo A. Madero", "lat": 19.4833, "lng": -99.1133,
        "resumen": "La alcaldía más poblada del norte. Precios de entrada bajos y buena conexión con el norte de la zona metropolitana y el aeropuerto.",
        "perfil": "Gustavo A. Madero es una alcaldía de vivienda popular y media con un inventario enorme y precios que abren la puerta a primeros compradores. Lindavista es su zona residencial más consolidada, con casas de los años sesenta y buena infraestructura comercial. Es un mercado de compra por necesidad y por presupuesto más que por estilo de vida.",
        "vive": "Líneas 3, 5 y 6 del Metro, además del Metrobús sobre Insurgentes Norte. Cercanía al Aeropuerto Internacional y a las salidas del norte de la ciudad.",
        "destacados": ["Lindavista", "Nueva Industrial Vallejo", "Aragón", "La Villa"],
    },
    {
        "slug": "iztacalco", "nombre": "Iztacalco", "lat": 19.3956, "lng": -99.0972,
        "resumen": "La alcaldía más compacta de la ciudad. Unidades habitacionales consolidadas y precio por metro cuadrado competitivo.",
        "perfil": "Iztacalco es pequeña y densa. Su inventario se compone principalmente de unidades habitacionales y departamentos de interés medio, con precios que la vuelven interesante para inversión de renta de ticket bajo. Granjas México y Agrícola Oriental son sus zonas más buscadas.",
        "vive": "Líneas 8 y 9 del Metro, acceso al Viaducto y cercanía al Foro Sol y la Ciudad Deportiva.",
        "destacados": ["Granjas México", "Agrícola Oriental", "Viaducto Piedad"],
    },
    {
        "slug": "iztapalapa", "nombre": "Iztapalapa", "lat": 19.3574, "lng": -99.0662,
        "resumen": "La alcaldía con mayor población del país. Mercado de vivienda de entrada, con desarrollos nuevos sobre los corredores del oriente.",
        "perfil": "Iztapalapa es el mercado de vivienda accesible más grande de la Ciudad de México. La oferta se concentra en casas de interés social y departamentos en desarrollos verticales sobre Ermita Iztapalapa y Tláhuac. Para inversión requiere un análisis muy fino de microzona: las diferencias de valor entre colonias vecinas son grandes.",
        "vive": "Líneas 8, A y 12 del Metro, además del Cablebús Línea 2. La Utopía Meyehualco y el Cerro de la Estrella son referencias del espacio público reciente.",
        "destacados": ["Ermita Zaragoza", "Cerro de la Estrella", "Santa Martha Acatitla"],
    },
    {
        "slug": "la-magdalena-contreras", "nombre": "La Magdalena Contreras", "lat": 19.3078, "lng": -99.2419,
        "resumen": "Bosque, barrancas y clima fresco al suroeste. Casas con terreno y una densidad muy baja para estar dentro de la ciudad.",
        "perfil": "La Magdalena Contreras es de las pocas alcaldías donde todavía se compran casas con terreno amplio y vegetación real sin salir de la Ciudad de México. San Jerónimo Lídice y La Cañada tienen un perfil residencial consolidado, con clima varios grados más fresco que el centro. Es una zona de compradores que buscan permanecer, no de rotación.",
        "vive": "Movilidad casi enteramente en auto, con acceso por Periférico Sur y San Jerónimo. Los Dinamos son el gran atractivo natural de la alcaldía.",
        "destacados": ["San Jerónimo Lídice", "La Cañada", "Tlalpuente"],
    },
    {
        "slug": "miguel-hidalgo", "nombre": "Miguel Hidalgo", "lat": 19.4326, "lng": -99.1950,
        "resumen": "La alcaldía con el ticket promedio más alto de la ciudad. Polanco, Lomas de Chapultepec y Bosques concentran el segmento premium.",
        "perfil": "Miguel Hidalgo es el segmento alto de la Ciudad de México. Polanco funciona como distrito de lujo vertical, con departamentos de 150 a 400 m², servicios de conserjería y una demanda internacional constante. Lomas de Chapultepec mantiene casas sobre terrenos de 600 a 1,500 m² con una plusvalía histórica sólida. Anzures y Escandón son las puertas de entrada más accesibles a la alcaldía. Aquí el diferenciador no es el precio, es la calidad del inmueble y la calle exacta.",
        "vive": "Chapultepec en las tres secciones, Polanquito, Presidente Masaryk y el corredor cultural de Reforma. Líneas 7 y 1 del Metro, Metrobús sobre Reforma y buena caminabilidad dentro de Polanco.",
        "destacados": ["Polanco", "Lomas de Chapultepec", "Anzures", "Escandón", "Bosques de las Lomas", "Granada"],
    },
    {
        "slug": "milpa-alta", "nombre": "Milpa Alta", "lat": 19.1922, "lng": -99.0231,
        "resumen": "La alcaldía más rural de la ciudad. Terrenos amplios, uso agrícola y un mercado inmobiliario muy particular.",
        "perfil": "Milpa Alta es la alcaldía menos urbanizada de la Ciudad de México. Su mercado se compone sobre todo de terrenos y casas de autoconstrucción, con una parte importante de suelo bajo régimen comunal o ejidal. Cualquier operación aquí requiere una revisión jurídica especialmente cuidadosa del régimen de propiedad.",
        "vive": "Vida de pueblo, clima frío y fuerte identidad comunitaria. Movilidad en auto o transporte concesionado hacia Tláhuac y Xochimilco.",
        "destacados": ["Villa Milpa Alta", "San Pedro Atocpan", "San Antonio Tecómitl"],
    },
    {
        "slug": "tlahuac", "nombre": "Tláhuac", "lat": 19.2878, "lng": -99.0056,
        "resumen": "Al sureste, con desarrollos de vivienda media y conexión por Línea 12 del Metro.",
        "perfil": "Tláhuac combina pueblos originarios con desarrollos de vivienda media construidos en las últimas dos décadas. Los precios son de los más accesibles de la ciudad. Es indispensable revisar el estudio de mecánica de suelo: buena parte de la alcaldía se asienta sobre suelo lacustre con hundimientos documentados.",
        "vive": "Línea 12 del Metro y acceso por la autopista del oriente de la ciudad. Fuerte tradición de pueblos y chinampas hacia la zona de Mixquic.",
        "destacados": ["Del Mar", "La Nopalera", "San Francisco Tlaltenco"],
    },
    {
        "slug": "tlalpan", "nombre": "Tlalpan", "lat": 19.2911, "lng": -99.1683,
        "resumen": "La alcaldía más extensa de la ciudad. Del centro histórico de Tlalpan a los fraccionamientos boscosos del sur.",
        "perfil": "Tlalpan es enorme y muy diversa. Su centro histórico conserva casonas coloniales alrededor de la plaza principal. Hacia el poniente, Fuentes del Pedregal y Jardines en la Montaña ofrecen casas en condominio con seguridad y terreno. Más al sur, la alcaldía se vuelve rural y se acerca al suelo de conservación.",
        "vive": "Línea 2 del Metro hasta Universidad y Metrobús sobre Insurgentes Sur. El Bosque de Tlalpan es uno de los mejores espacios deportivos al aire libre de la ciudad.",
        "destacados": ["Tlalpan Centro", "Fuentes del Pedregal", "Jardines en la Montaña", "Toriello Guerra"],
    },
    {
        "slug": "venustiano-carranza", "nombre": "Venustiano Carranza", "lat": 19.4247, "lng": -99.1092,
        "resumen": "Alcaldía céntrica con acceso directo al aeropuerto y al Centro Histórico. Mercado de renta corta con potencial.",
        "perfil": "Venustiano Carranza tiene una ubicación estratégica poco aprovechada: colinda con el Centro Histórico y aloja el Aeropuerto Internacional. Colonias como Jardín Balbuena y Moctezuma tienen vivienda de los años cincuenta y sesenta a precios muy por debajo del promedio de las alcaldías centrales, con potencial de renta corporativa y de estancia media.",
        "vive": "Líneas 1, 4, 5, 9 y B del Metro. Jardín Balbuena es la colonia más arbolada y residencial de la alcaldía.",
        "destacados": ["Jardín Balbuena", "Moctezuma", "Merced Balbuena", "Aeronáutica Militar"],
    },
    {
        "slug": "xochimilco", "nombre": "Xochimilco", "lat": 19.2572, "lng": -99.1031,
        "resumen": "Patrimonio de la Humanidad, chinampas y zonas residenciales al sur. Un mercado de nicho con reglas propias.",
        "perfil": "Xochimilco combina el área patrimonial de canales y chinampas con fraccionamientos residenciales como Rinconada Coapa y Prados de Coyoacán. El suelo de conservación cubre gran parte de la alcaldía, lo que limita el desarrollo y exige verificar uso de suelo antes de cualquier operación.",
        "vive": "Tren Ligero desde Tasqueña y acceso por Prolongación División del Norte. Vida de barrio, mercados y la actividad turística de los embarcaderos.",
        "destacados": ["Rinconada Coapa", "Prados de Coyoacán", "Barrio San Marcos", "Huichapan"],
    },
]

ALCALDIA_BY_SLUG = {a["slug"]: a for a in ALCALDIAS}
ALCALDIA_SLUG_BY_NOMBRE = {a["nombre"]: a["slug"] for a in ALCALDIAS}


# ---------------------------------------------------------------- colonias
# Landing pages SEO de colonias prioritarias. Todas dentro de CDMX.
COLONIAS = [
    {
        "slug": "polanco", "nombre": "Polanco", "alcaldia": "Miguel Hidalgo",
        "lat": 19.4333, "lng": -99.1950, "cp": ["11510", "11550", "11560"],
        "tagline": "El distrito premium de la Ciudad de México.",
        "precio_m2_venta": 92000, "precio_m2_renta": 420,
        "vivir": "Polanco es la única zona de la ciudad donde puedes salir a comer, ir a una galería, dejar a los niños en la escuela y regresar caminando. Las secciones I a V tienen personalidades distintas: Polanco I y II concentran la vida comercial de Masaryk y Polanquito; Polanco III y IV son más residenciales y arboladas; Polanco V colinda con Chapultepec y tiene los edificios más nuevos. El ruido y el tráfico son el precio de esa centralidad.",
        "tipo_oferta": "Predomina el departamento de 120 a 350 m² en edificios de 6 a 20 niveles, con conserjería, seguridad y amenidades. También hay penthouses de gran formato y algunas casas remanentes en Polanco Chapultepec.",
        "movilidad": "Metro Polanco y Auditorio (Línea 7), Metrobús sobre Reforma, Ecobici en casi toda la colonia. Acceso rápido a Periférico y Reforma.",
        "restaurantes": "Presidente Masaryk, Emilio Castelar y la zona de Polanquito concentran la mayor densidad gastronómica del país.",
        "parques": "Parque Lincoln, Parque América y acceso directo a la Primera Sección del Bosque de Chapultepec.",
        "escuelas": "Colegios privados bilingües en un radio de 15 minutos, además de la oferta cultural del Museo Soumaya, Jumex y Antropología.",
        "servicios": "Antara Fashion Hall, Plaza Carso, hospitales privados y oficinas corporativas sobre Ejército Nacional.",
    },
    {
        "slug": "lomas-de-chapultepec", "nombre": "Lomas de Chapultepec", "alcaldia": "Miguel Hidalgo",
        "lat": 19.4230, "lng": -99.2130, "cp": ["11000", "11010", "11020"],
        "tagline": "Casas con terreno y una plusvalía que se sostiene desde hace décadas.",
        "precio_m2_venta": 88000, "precio_m2_renta": 350,
        "vivir": "Lomas es una colonia de casas, no de edificios. Calles anchas, arbolado maduro y terrenos que van de 600 a más de 2,000 m². Se vive con auto, con privacidad y con una tranquilidad que no existe en Polanco. Es el destino natural de familias que necesitan espacio y no quieren salir del poniente.",
        "tipo_oferta": "Casas sobre terrenos amplios, algunas remodeladas y otras en estado original con potencial de redesarrollo. Oferta creciente de departamentos de gran formato sobre Reforma y Palmas.",
        "movilidad": "Acceso por Paseo de la Reforma, Palmas y Periférico. Transporte público limitado: es una zona pensada para el automóvil.",
        "restaurantes": "Corredor de Palmas y Virreyes, además de la oferta de Bosques y Polanco a menos de 10 minutos.",
        "parques": "Segunda y Tercera Sección de Chapultepec, Parque Bosque de las Lomas y el Panteón Francés como pulmón inesperado.",
        "escuelas": "Alta concentración de colegios internacionales y bilingües en el corredor Palmas–Bosques.",
        "servicios": "Embajadas, corporativos sobre Reforma Lomas, hospitales privados y comercio de barrio sobre Monte Líbano.",
    },
    {
        "slug": "condesa", "nombre": "Condesa", "alcaldia": "Cuauhtémoc",
        "lat": 19.4110, "lng": -99.1740, "cp": ["06140"],
        "tagline": "Arquitectura art déco, camellones arbolados y la mejor caminabilidad de la ciudad.",
        "precio_m2_venta": 74000, "precio_m2_renta": 330,
        "vivir": "Condesa se vive a pie. Es la zona donde más gente prescinde del auto entre semana. Edificios de los años treinta con dobles alturas, herrería original y pisos de duela conviven con obra nueva de departamentos compactos. A cambio, hay que asumir vida nocturna, escasez de estacionamiento y edificios que exigen revisión estructural cuidadosa.",
        "tipo_oferta": "Departamentos de 60 a 180 m², muchos en edificios catalogados. Lofts y penthouses con terraza sobre Amsterdam, Michoacán y Mazatlán.",
        "movilidad": "Metro Chilpancingo y Patriotismo (Línea 9), Metrobús sobre Insurgentes, red densa de Ecobici y ciclovías.",
        "restaurantes": "Michoacán, Tamaulipas y Nuevo León concentran la oferta gastronómica; es una de las zonas con mayor rotación de nuevos conceptos.",
        "parques": "Parque México y Parque España, además del Foro Lindbergh como centro de vida social de la colonia.",
        "escuelas": "Oferta educativa privada de tamaño medio y cercanía a universidades sobre Insurgentes.",
        "servicios": "Comercio independiente, librerías, gimnasios boutique y una escena cultural constante.",
    },
    {
        "slug": "hipodromo-condesa", "nombre": "Hipódromo Condesa", "alcaldia": "Cuauhtémoc",
        "lat": 19.4090, "lng": -99.1720, "cp": ["06100"],
        "tagline": "El trazado ovalado del antiguo hipódromo, convertido en la colonia mejor diseñada de la ciudad.",
        "precio_m2_venta": 78000, "precio_m2_renta": 345,
        "vivir": "Hipódromo comparte el ADN de Condesa pero es más residencial y silenciosa. El trazado curvo de Amsterdam y Ámsterdam-México genera calles sin tráfico de paso. Es la zona preferida por quien quiere la vida de Condesa sin el ruido de los corredores gastronómicos.",
        "tipo_oferta": "Departamentos art déco y funcionalistas de 70 a 200 m², buena proporción con terraza o balcón. Obra nueva escasa y muy demandada.",
        "movilidad": "Metrobús Sonora y Campeche, Metro Chilpancingo, Ecobici y calles diseñadas para caminar.",
        "restaurantes": "Campeche, Ámsterdam y Nuevo León, con perfil de cafés de especialidad y cocina de autor.",
        "parques": "Parque México es el corazón de la colonia: perros, corredores, clases al aire libre y conciertos en el Foro Lindbergh.",
        "escuelas": "Colegios pequeños de perfil progresista y cercanía a la oferta educativa de Roma y Del Valle.",
        "servicios": "Comercio de proximidad, mercado de Michoacán y servicios médicos sobre Insurgentes.",
    },
    {
        "slug": "roma-norte", "nombre": "Roma Norte", "alcaldia": "Cuauhtémoc",
        "lat": 19.4180, "lng": -99.1620, "cp": ["06700"],
        "tagline": "Galerías, porfiriato y la mayor rotación de renta de la ciudad.",
        "precio_m2_venta": 72000, "precio_m2_renta": 340,
        "vivir": "Roma Norte es la colonia más internacional de la ciudad. Casonas porfirianas convertidas en oficinas creativas, galerías, cafés de especialidad y una comunidad muy diversa. Para inversión de renta es probablemente la zona más líquida de la Ciudad de México: una propiedad bien ubicada rara vez pasa más de un mes desocupada.",
        "tipo_oferta": "Departamentos de 55 a 160 m², desde restauraciones de edificios antiguos hasta obra nueva con roof garden. Alta demanda de estudios y de una recámara.",
        "movilidad": "Metro Insurgentes y Hospital General, Metrobús sobre Insurgentes, Ecobici en toda la colonia y una de las redes de ciclovía más completas.",
        "restaurantes": "Álvaro Obregón, Colima, Orizaba y Córdoba. Es el epicentro de la escena gastronómica contemporánea del país.",
        "parques": "Plaza Río de Janeiro, Plaza Luis Cabrera y Jardín Pushkin.",
        "escuelas": "Cercanía a universidades y centros culturales; oferta de educación básica privada moderada.",
        "servicios": "Mercado Medellín, galerías de arte, coworkings y comercio de diseño independiente.",
    },
    {
        "slug": "roma-sur", "nombre": "Roma Sur", "alcaldia": "Cuauhtémoc",
        "lat": 19.4050, "lng": -99.1610, "cp": ["06760"],
        "tagline": "La versión tranquila y más accesible de la Roma.",
        "precio_m2_venta": 61000, "precio_m2_renta": 275,
        "vivir": "Roma Sur ofrece prácticamente los mismos servicios que Roma Norte con precios entre 15 y 25 por ciento menores. Es más residencial, con menos flujo turístico y una vida de barrio que se conserva alrededor del Mercado Medellín y la calle Coahuila. Para primer departamento es de las mejores relaciones ubicación-precio del centro de la ciudad.",
        "tipo_oferta": "Departamentos de 60 a 140 m², mezcla de edificios de los cincuenta y sesenta con obra nueva de escala media.",
        "movilidad": "Metro Chilpancingo y Centro Médico, Metrobús sobre Insurgentes y Doctor Vértiz.",
        "restaurantes": "Mercado Medellín, cocina peruana y cubana sobre Campeche, y la expansión gastronómica que baja desde Roma Norte.",
        "parques": "Parque Ramón López Velarde y jardines de barrio sobre Zacatecas.",
        "escuelas": "Oferta educativa pública y privada de escala local, con universidades a corta distancia.",
        "servicios": "Centro Médico Nacional a pocos minutos, comercio tradicional y talleres de oficio.",
    },
    {
        "slug": "juarez", "nombre": "Juárez", "alcaldia": "Cuauhtémoc",
        "lat": 19.4270, "lng": -99.1610, "cp": ["06600"],
        "tagline": "Entre Reforma y la Zona Rosa: la colonia que se está reinventando.",
        "precio_m2_venta": 68000, "precio_m2_renta": 300,
        "vivir": "Juárez vive un proceso de renovación notable. Edificios antiguos rehabilitados, hoteles boutique y una escena gastronómica que creció alrededor de Havre y Versalles. Su gran ventaja es la ubicación: Reforma de un lado, Roma del otro y el Centro Histórico a quince minutos caminando. Su desafío es la convivencia con la vida nocturna de la Zona Rosa.",
        "tipo_oferta": "Departamentos de 50 a 150 m² en edificios rehabilitados y obra nueva vertical sobre Reforma con amenidades completas.",
        "movilidad": "Metro Insurgentes y Cuauhtémoc, Metrobús sobre Reforma, y una de las mejores conexiones de la ciudad hacia cualquier punto.",
        "restaurantes": "Havre, Versalles y Génova, con oferta que va del comercio coreano de la Zona Rosa a la cocina de autor.",
        "parques": "Jardín del Arte, Glorieta de las Cibeles y acceso directo a Chapultepec por Reforma.",
        "escuelas": "Perfil más corporativo que familiar; oferta educativa cercana en Roma y Condesa.",
        "servicios": "Corredor financiero de Reforma, hoteles, embajadas y centros culturales.",
    },
    {
        "slug": "del-valle", "nombre": "Del Valle", "alcaldia": "Benito Juárez",
        "lat": 19.3860, "lng": -99.1690, "cp": ["03100", "03103", "03104"],
        "tagline": "La colonia más equilibrada de la ciudad para vivir con familia.",
        "precio_m2_venta": 63000, "precio_m2_renta": 255,
        "vivir": "Del Valle funciona. Tiene escuelas, hospitales, mercados, parques y transporte, todo dentro de la misma colonia. Es amplia y conviene distinguir sus tres secciones: Del Valle Centro es la más consolidada y cara; Del Valle Norte se acerca a Nápoles y a la vida de Insurgentes; Del Valle Sur es más tranquila y con mejor precio. Es la zona a la que más clientes regresan después de comparar.",
        "tipo_oferta": "Departamentos de 80 a 200 m² en edificios de 4 a 12 niveles, con estacionamiento y elevador. Casas remanentes de los cincuenta en las calles interiores.",
        "movilidad": "Metro División del Norte y Zapata (Línea 3 y 12), Metrobús sobre Insurgentes y Félix Cuevas. Muy caminable dentro de la colonia.",
        "restaurantes": "Corredor de Félix Cuevas, Providencia y Amores. Cocina de barrio consolidada más nuevos conceptos.",
        "parques": "Parque Tlacoquemécatl, Parque Hundido a pocos minutos y el Parque de los Venados.",
        "escuelas": "Una de las mayores concentraciones de colegios privados de nivel básico y medio de la ciudad.",
        "servicios": "Mercado de Mixcoac, Plaza Universidad, hospitales privados y consultorios sobre Coyoacán y Xola.",
    },
    {
        "slug": "narvarte", "nombre": "Narvarte", "alcaldia": "Benito Juárez",
        "lat": 19.3950, "lng": -99.1550, "cp": ["03020", "03023"],
        "tagline": "El mejor precio por metro cuadrado entre las colonias céntricas consolidadas.",
        "precio_m2_venta": 54000, "precio_m2_renta": 225,
        "vivir": "Narvarte tiene todo lo que necesita una colonia céntrica y cuesta considerablemente menos que Roma o Del Valle. Su arquitectura de los cincuenta y sesenta ofrece departamentos con distribuciones generosas y ventanas amplias. En los últimos años ha ganado una escena gastronómica propia sobre Diagonal San Antonio y Universidad.",
        "tipo_oferta": "Departamentos de 70 a 150 m². Excelente inventario de tres recámaras con precio por debajo del promedio de la zona centro-sur.",
        "movilidad": "Metro Etiopía, Eugenia y Centro Médico. Metrobús sobre Insurgentes y Eje 4 Sur.",
        "restaurantes": "Diagonal San Antonio, Torres Adalid y Xola. Taquerías históricas y cocina contemporánea sin sobreprecio.",
        "parques": "Parque de los Venados, Parque Tlacoquemécatl y el Parque Delta como centro comercial y espacio abierto.",
        "escuelas": "Colegios privados de escala media y buena conexión con la oferta educativa de Del Valle.",
        "servicios": "Centro Médico Nacional, Parque Delta, mercados públicos y comercio de proximidad.",
    },
    {
        "slug": "napoles", "nombre": "Nápoles", "alcaldia": "Benito Juárez",
        "lat": 19.3960, "lng": -99.1780, "cp": ["03810"],
        "tagline": "Ubicación estratégica junto al World Trade Center y Parque Hundido.",
        "precio_m2_venta": 66000, "precio_m2_renta": 270,
        "vivir": "Nápoles combina vocación residencial con corredor de oficinas. La cercanía al World Trade Center y a Insurgentes la hace atractiva para quien busca reducir traslados. Es una colonia ordenada, con calles arboladas y edificios de escala media, y con una de las mejores relaciones ubicación-precio de Benito Juárez.",
        "tipo_oferta": "Departamentos de 80 a 180 m², oferta creciente de obra nueva vertical con amenidades sobre Insurgentes y Dakota.",
        "movilidad": "Metro San Antonio y Mixcoac, Metrobús Poliforum y Nápoles sobre Insurgentes.",
        "restaurantes": "Corredor de Pennsylvania y Georgia, además de la oferta del World Trade Center.",
        "parques": "Parque Hundido, uno de los espacios más arbolados del centro-sur de la ciudad.",
        "escuelas": "Oferta educativa privada compartida con Del Valle e Insurgentes Mixcoac.",
        "servicios": "World Trade Center, Polyforum Siqueiros, hoteles de negocios y comercio sobre Insurgentes.",
    },
    {
        "slug": "portales", "nombre": "Portales", "alcaldia": "Benito Juárez",
        "lat": 19.3690, "lng": -99.1470, "cp": ["03300", "03570"],
        "tagline": "Vida de barrio auténtica con precios de entrada dentro de Benito Juárez.",
        "precio_m2_venta": 47000, "precio_m2_renta": 200,
        "vivir": "Portales conserva una vida de barrio que se ha perdido en otras colonias de Benito Juárez: mercado público activo, taquerías con décadas de historia y vecinos de toda la vida. Es de las opciones más accesibles para comprar dentro de una alcaldía con servicios completos, y ha ganado plusvalía de forma constante en los últimos años.",
        "tipo_oferta": "Departamentos de 60 a 120 m² y casas de los sesenta con posibilidad de remodelación. Obra nueva de escala media sobre Ermita y Municipio Libre.",
        "movilidad": "Metro Portales y Ermita (Línea 2), acceso a Eje Central y Calzada de Tlalpan.",
        "restaurantes": "Mercado de Portales y el corredor taquero de Eje Central, con una de las mejores ofertas de comida tradicional de la ciudad.",
        "parques": "Parque de los Venados a corta distancia y jardines de barrio sobre Eje 7A Sur.",
        "escuelas": "Oferta educativa pública consolidada y colegios privados de escala local.",
        "servicios": "Mercado de Portales, comercio de barrio y servicios médicos sobre Municipio Libre.",
    },
    {
        "slug": "insurgentes-mixcoac", "nombre": "Insurgentes Mixcoac", "alcaldia": "Benito Juárez",
        "lat": 19.3750, "lng": -99.1880, "cp": ["03920"],
        "tagline": "Nodo de transporte, universidades y renovación urbana.",
        "precio_m2_venta": 58000, "precio_m2_renta": 245,
        "vivir": "Insurgentes Mixcoac tiene una de las mejores conectividades de la ciudad: cruce de Metro Línea 7 y 12, Metrobús y Periférico. Alrededor del antiguo pueblo de Mixcoac se conserva un núcleo histórico con plaza, iglesia y calles empedradas que contrasta con la actividad de Insurgentes Sur. Es zona de fuerte demanda de renta por la presencia universitaria.",
        "tipo_oferta": "Departamentos de 60 a 140 m², obra nueva vertical sobre Insurgentes y Extremadura, más casas antiguas en el pueblo de Mixcoac.",
        "movilidad": "Metro Mixcoac (Líneas 7 y 12), Metrobús Insurgentes, acceso directo a Periférico y Río Mixcoac.",
        "restaurantes": "Corredor de Extremadura, Plaza Mixcoac y la oferta del pueblo histórico.",
        "parques": "Parque Hundido y el Parque Miguel Alemán, además del Deportivo Plan Sexenal.",
        "escuelas": "Universidades privadas de primer nivel y colegios de nivel básico en Del Valle y Mixcoac.",
        "servicios": "Plaza Mixcoac, Patio Universidad y una densidad comercial alta sobre Insurgentes.",
    },
    {
        "slug": "anzures", "nombre": "Anzures", "alcaldia": "Miguel Hidalgo",
        "lat": 19.4290, "lng": -99.1770, "cp": ["11590"],
        "tagline": "La puerta de entrada más accesible a Miguel Hidalgo.",
        "precio_m2_venta": 64000, "precio_m2_renta": 275,
        "vivir": "Anzures está a diez minutos caminando de Polanco y cuesta significativamente menos. Es una colonia de escala media, con edificios de los sesenta y setenta, embajadas y una vida comercial discreta. Para quien quiere ubicación de Miguel Hidalgo sin el ticket de Polanco, es la respuesta más lógica.",
        "tipo_oferta": "Departamentos de 70 a 180 m², varios con distribuciones amplias y en proceso de remodelación integral.",
        "movilidad": "Metro Chapultepec y Sevilla, Metrobús sobre Reforma, Ecobici y acceso a Circuito Interior.",
        "restaurantes": "Corredor de Leibnitz y Sudermann, además de toda la oferta de Polanco a corta distancia.",
        "parques": "Bosque de Chapultepec Primera Sección y Parque América en Polanco.",
        "escuelas": "Colegios en Polanco y Cuauhtémoc a menos de 15 minutos.",
        "servicios": "Embajadas, corporativos sobre Reforma y comercio de proximidad sobre Melchor Ocampo.",
    },
    {
        "slug": "escandon", "nombre": "Escandón", "alcaldia": "Miguel Hidalgo",
        "lat": 19.4030, "lng": -99.1810, "cp": ["11800"],
        "tagline": "Barrio tradicional con obra nueva y precios todavía razonables.",
        "precio_m2_venta": 56000, "precio_m2_renta": 240,
        "vivir": "Escandón es de las colonias que más han cambiado en la última década. Su cercanía con Condesa y San Pedro de los Pinos atrajo obra nueva de escala media y una escena gastronómica joven, sin perder la vida de barrio del mercado y las vecindades. Es una de las mejores apuestas de plusvalía en Miguel Hidalgo.",
        "tipo_oferta": "Departamentos nuevos de 55 a 120 m² con roof garden y amenidades, junto a inventario de los cincuenta con buenos metros.",
        "movilidad": "Metro Patriotismo y Juanacatlán, Metrobús sobre Patriotismo, acceso a Viaducto y Circuito Interior.",
        "restaurantes": "Mercado Escandón, corredor de José Martí y la oferta de Condesa cruzando Patriotismo.",
        "parques": "Parque Ignacio Chávez y Parque España a corta distancia.",
        "escuelas": "Oferta educativa de escala local con acceso rápido a colegios de Condesa y San Pedro de los Pinos.",
        "servicios": "Mercado Escandón, comercio tradicional y servicios médicos sobre Patriotismo.",
    },
    {
        "slug": "santa-fe", "nombre": "Santa Fe", "alcaldia": "Cuajimalpa de Morelos",
        "lat": 19.3600, "lng": -99.2600, "cp": ["05348", "05300"],
        "tagline": "Vivienda vertical contemporánea con amenidades completas y las mejores vistas del poniente.",
        "precio_m2_venta": 59000, "precio_m2_renta": 265,
        "vivir": "Santa Fe funciona con una lógica propia: torres residenciales con seguridad 24/7, gimnasio, alberca, salón de eventos y servicios dentro del mismo conjunto. Es la zona con el inventario más nuevo de la ciudad y la que mejor resuelve la vida de quien trabaja en el corredor corporativo del poniente. La contrapartida es la dependencia del automóvil y el tráfico en horas pico.",
        "tipo_oferta": "Departamentos de 80 a 250 m² en torres de 15 a 40 niveles, casi todos con amenidades completas y estacionamiento múltiple.",
        "movilidad": "Acceso por Carlos Lazo, Vasco de Quiroga y la salida poniente de la ciudad. Transporte concesionado y rutas corporativas; el auto sigue siendo indispensable.",
        "restaurantes": "Centro Santa Fe, Park Plaza, Garden Santa Fe y la oferta gastronómica dentro de los corporativos.",
        "parques": "Parque La Mexicana, uno de los mejores espacios públicos construidos en la ciudad en los últimos años.",
        "escuelas": "Universidades privadas de primer nivel y colegios internacionales dentro de la zona.",
        "servicios": "Centro Santa Fe, hospitales privados, corporativos y centros de convenciones.",
    },
    {
        "slug": "bosques-de-las-lomas", "nombre": "Bosques de las Lomas", "alcaldia": "Miguel Hidalgo",
        "lat": 19.3930, "lng": -99.2610, "cp": ["05120"],
        "tagline": "Barrancas arboladas, casas de gran formato y clima fresco dentro de la ciudad.",
        "precio_m2_venta": 79000, "precio_m2_renta": 320,
        "vivir": "Bosques está construida sobre barrancas, lo que le da una topografía y un arbolado que ninguna otra zona premium tiene. Las casas se aprovechan de los desniveles con terrazas y vistas amplias. Es una zona residencial silenciosa, con acceso rápido a Santa Fe y a Palmas, y con muy poca vida peatonal.",
        "tipo_oferta": "Casas de 400 a 900 m² de construcción y departamentos de gran formato en edificios de baja densidad.",
        "movilidad": "Acceso por Palmas, Bosques de Reforma y Periférico. Zona pensada para el automóvil.",
        "restaurantes": "Corredor de Bosques de Duraznos y Plaza Bosques, además de Santa Fe y Palmas a corta distancia.",
        "parques": "Barrancas arboladas, Parque La Mexicana y Tercera Sección de Chapultepec.",
        "escuelas": "Colegios internacionales sobre el corredor Palmas–Bosques–Santa Fe.",
        "servicios": "Corporativos sobre Bosques de Alisos, hospitales privados y centros comerciales de la zona poniente.",
    },
    {
        "slug": "pedregal", "nombre": "Jardines del Pedregal", "alcaldia": "Álvaro Obregón",
        "lat": 19.3200, "lng": -99.2050, "cp": ["01900"],
        "tagline": "Arquitectura moderna mexicana sobre roca volcánica y los terrenos más amplios de la ciudad.",
        "precio_m2_venta": 71000, "precio_m2_renta": 290,
        "vivir": "El Pedregal es un caso único: un fraccionamiento diseñado sobre lava volcánica que dio origen a algunas de las mejores casas modernas de México. Terrenos de 800 a 2,500 m², muros de piedra volcánica y vegetación endémica. Es una zona de baja densidad, muy silenciosa, donde el valor está tanto en el terreno como en la arquitectura.",
        "tipo_oferta": "Casas de 350 a 1,200 m² de construcción, muchas de autor. Terrenos con potencial de obra nueva y algunas casas en condominio horizontal.",
        "movilidad": "Acceso por Periférico Sur, Insurgentes Sur y San Jerónimo. Transporte público limitado.",
        "restaurantes": "Corredor de Altavista y San Ángel, además de Perisur y la oferta de Insurgentes Sur.",
        "parques": "Espacios Escultóricos de la UNAM, Reserva del Pedregal de San Ángel y jardines privados de gran tamaño.",
        "escuelas": "Colegios privados de primer nivel y proximidad a Ciudad Universitaria.",
        "servicios": "Perisur, hospitales privados del sur y centros culturales de la UNAM.",
    },
    {
        "slug": "san-angel", "nombre": "San Ángel", "alcaldia": "Álvaro Obregón",
        "lat": 19.3460, "lng": -99.1900, "cp": ["01000"],
        "tagline": "Empedrados, casonas coloniales y una de las zonas con más carácter de la ciudad.",
        "precio_m2_venta": 76000, "precio_m2_renta": 300,
        "vivir": "San Ángel se vive despacio. Calles empedradas, bugambilias, muros de piedra y una escala de pueblo que sobrevivió al crecimiento de la ciudad. Las propiedades son en su mayoría casas, muchas catalogadas por el INAH, lo que implica reglas específicas para cualquier intervención. Es una compra emocional que además ha demostrado una plusvalía muy sólida.",
        "tipo_oferta": "Casas coloniales y de mediados de siglo con jardín, además de departamentos de baja densidad en Altavista y Chimalistac.",
        "movilidad": "Metrobús sobre Insurgentes Sur, acceso por Revolución y Periférico. Interior de la zona muy caminable.",
        "restaurantes": "Avenida de la Paz y Altavista concentran una de las ofertas gastronómicas más consolidadas del sur.",
        "parques": "Parque de la Bombilla, Plaza San Jacinto y los jardines del Museo Casa del Risco.",
        "escuelas": "Colegios privados tradicionales y cercanía a universidades del sur.",
        "servicios": "Bazar del Sábado, Plaza Loreto, museos Casa Estudio Diego Rivera y Carrillo Gil.",
    },
    {
        "slug": "coyoacan", "nombre": "Coyoacán", "alcaldia": "Coyoacán",
        "lat": 19.3500, "lng": -99.1620, "cp": ["04000", "04100"],
        "tagline": "Casas con jardín, vida cultural y un centro histórico que sigue siendo barrio.",
        "precio_m2_venta": 65000, "precio_m2_renta": 265,
        "vivir": "El centro de Coyoacán conserva algo que casi ninguna otra zona de la ciudad tiene: gente que sale a la plaza. Villa Coyoacán, Del Carmen y Santa Catarina ofrecen casas con jardín en calles arboladas, a pocas cuadras de mercados, librerías y museos. Es una zona de compradores que se quedan muchos años.",
        "tipo_oferta": "Casas de 200 a 500 m² de construcción con jardín, además de departamentos de baja densidad en Romero de Terreros y Copilco.",
        "movilidad": "Metro Coyoacán y Viveros (Línea 3), Metrobús sobre Insurgentes. Interior muy caminable, aunque se recomienda auto para trayectos largos.",
        "restaurantes": "Mercado de Coyoacán, corredor de Higuera y Francisco Sosa, y la oferta de Avenida México.",
        "parques": "Viveros de Coyoacán, Jardín Centenario, Plaza Hidalgo y Parque Frida Kahlo.",
        "escuelas": "Colegios tradicionales del sur y cercanía a Ciudad Universitaria.",
        "servicios": "Museo Frida Kahlo, Museo Casa de León Trotsky, mercados públicos y comercio cultural.",
    },
]

COLONIA_BY_SLUG = {c["slug"]: c for c in COLONIAS}
