# -*- coding: utf-8 -*-
"""Gio Filio — Contenido editorial: blog, testimonios, proceso, FAQs."""

TESTIMONIOS = [
    dict(nombre="Mariana R.", contexto="Compró departamento en Del Valle",
         texto="Llevaba ocho meses viendo departamentos sola y todos me parecían iguales. Gio me hizo tres preguntas sobre mi rutina y descartó la mitad de mi lista en una tarde. Terminé comprando en una calle que ni siquiera había considerado, y hoy no me imagino viviendo en otro lado."),
    dict(nombre="Andrés y Paola", contexto="Rentaron en Roma Norte",
         texto="Buscábamos algo que aceptara dos perros grandes, que es prácticamente imposible en la Roma. Gio filtró por eso desde el primer día en lugar de mostrarnos cosas que luego iban a rechazarnos. Firmamos en tres semanas."),
    dict(nombre="Fernanda G.", contexto="Vendió casa en Coyoacán",
         texto="Me habían dicho que mi casa valía cuatro millones más de lo que finalmente se vendió, y por eso llevaba catorce meses en el mercado con otra asesora. Gio me mostró los comparables reales, ajustamos el precio y se vendió en siete semanas."),
    dict(nombre="Roberto M.", contexto="Inversión en Narvarte",
         texto="Yo llegué queriendo comprar en Polanco porque sonaba bien. Gio me armó una comparación de rendimiento entre Polanco, Roma Sur y Narvarte con números reales de renta. Compré dos departamentos en Narvarte y ambos se rentaron antes de que terminara la escrituración."),
    dict(nombre="Lucía T.", contexto="Compró su primer departamento en Portales",
         texto="Era mi primera compra y no entendía nada del proceso. Gio me explicó lo del crédito, el avalúo, la escrituración y los gastos de cierre antes de que empezáramos a ver propiedades, no después. Eso cambió por completo mi presupuesto real."),
    dict(nombre="Familia Escobar", contexto="Compró casa en San Ángel",
         texto="La casa que compramos está catalogada y eso nos daba mucho miedo. Gio nos consiguió la información del INAH, nos conectó con un arquitecto que ya había trabajado en la zona y nos acompañó a las reuniones. Nunca sentimos que nos estuviera empujando a cerrar."),
]

PROCESO = {
    "comprar": dict(
        titulo="Comprar",
        intro="Comprar en la Ciudad de México toma en promedio entre tres y seis meses. La mayor parte de ese tiempo se puede reducir si las primeras conversaciones son las correctas.",
        pasos=[
            ("Conversación inicial", "Antes de ver una sola propiedad hablamos de cómo vives: horarios, traslados, si tienes hijos o mascotas, si trabajas desde casa, cuánto tiempo planeas quedarte. De ahí sale el filtro real."),
            ("Presupuesto y capacidad", "Revisamos el enganche disponible, la capacidad de crédito y, muy importante, los gastos de cierre: escrituración, avalúo, ISAI y comisiones bancarias suelen representar entre 6 y 8 por ciento adicional."),
            ("Selección corta", "Te presento entre cinco y ocho propiedades, no cuarenta. Cada una con una razón concreta de por qué está en la lista y qué le veo de riesgo."),
            ("Visitas y comparación", "Recorremos juntos. Después de cada visita anotamos lo que funcionó y lo que no, y ajustamos el filtro."),
            ("Oferta y negociación", "Preparo un análisis de comparables de los últimos doce meses para sustentar la oferta. Negocio precio, condiciones, inclusiones y tiempos."),
            ("Revisión documental", "Escrituras, predial, agua, régimen de condominio, certificado de libertad de gravamen, uso de suelo. Aquí es donde se detectan los problemas que después cuestan caro."),
            ("Cierre y escrituración", "Coordinación con notaría, banco y vendedor hasta la firma y entrega de llaves."),
        ]),
    "rentar": dict(
        titulo="Rentar",
        intro="Rentar bien es sobre todo cuestión de velocidad y de tener los papeles listos. En zonas como Roma, Condesa o Del Valle, una buena propiedad se coloca en menos de dos semanas.",
        pasos=[
            ("Definir el filtro real", "Presupuesto total, incluyendo mantenimiento y servicios. Zona, mascotas, estacionamiento, amueblado o no, y fecha real de mudanza."),
            ("Preparar el expediente", "Identificación, comprobantes de ingreso, aval o póliza jurídica. Tener esto listo antes de buscar es la diferencia entre quedarte con la propiedad o perderla."),
            ("Selección y visitas", "Te muestro opciones que ya verifiqué que aceptan tus condiciones. No pierdes tiempo en propiedades que van a rechazarte."),
            ("Negociación del contrato", "Renta, incrementos anuales, depósito, plazo, quién paga qué mantenimiento y condiciones de salida. Todo por escrito."),
            ("Firma y entrega", "Inventario fotográfico del estado del inmueble al momento de la entrega. Esto protege tu depósito al final del contrato."),
        ]),
    "vender": dict(
        titulo="Vender",
        intro="La mayoría de las propiedades que llevan más de seis meses en el mercado tienen el mismo problema, y no es la propiedad: es el precio de salida.",
        pasos=[
            ("Valoración con comparables", "Analizo operaciones cerradas de los últimos doce meses en tu colonia, no precios de lista. La diferencia entre ambos suele ser del 5 al 12 por ciento."),
            ("Preparación del inmueble", "Recomendaciones concretas de bajo costo y alto impacto: pintura, iluminación, orden y pequeñas reparaciones. Es la inversión con mejor retorno del proceso."),
            ("Material profesional", "Fotografía profesional, plano arquitectónico y recorrido virtual. Una propiedad con buen material recibe entre dos y tres veces más solicitudes."),
            ("Estrategia de difusión", "Publicación en portales, redes, base de clientes propia y red de colegas. Filtro las solicitudes para que solo recibas visitas de prospectos calificados."),
            ("Negociación", "Manejo las ofertas, las contraofertas y las condiciones. Tú decides; yo te doy el contexto de mercado para decidir bien."),
            ("Cierre", "Coordinación notarial, revisión documental y acompañamiento hasta la firma."),
        ]),
    "invertir": dict(
        titulo="Invertir",
        intro="Una propiedad de inversión se compra con hoja de cálculo, no con emoción. La pregunta correcta no es dónde te gustaría vivir, sino qué se renta rápido y a quién.",
        pasos=[
            ("Definir el objetivo", "Flujo mensual, plusvalía de mediano plazo o una combinación. Cada objetivo apunta a zonas y productos distintos."),
            ("Análisis de zona", "Comparo precio por metro cuadrado, renta promedio, vacancia histórica y proyectos de infraestructura en curso."),
            ("Selección del producto", "En renta larga, los estudios y las unidades de una o dos recámaras cerca de transporte son los más líquidos. En preventa, la variable clave es el desarrollador."),
            ("Números reales", "Rendimiento bruto y neto considerando mantenimiento, predial, seguro, vacancia estimada y administración. Sin esos descuentos, el número no sirve."),
            ("Compra y colocación", "Acompaño la compra y después la colocación del inquilino, incluyendo la póliza jurídica."),
        ]),
}

FAQS_GENERALES = [
    ("¿Gio Filio trabaja solo en Ciudad de México?",
     "Sí. Toda la asesoría y el inventario se concentran exclusivamente en las 16 alcaldías de la Ciudad de México. Conocer bien un mercado vale más que cubrir muchos de forma superficial."),
    ("¿Cuánto cuesta la asesoría para comprar o rentar?",
     "Para el comprador o el inquilino, la asesoría no tiene costo directo: la comisión la cubre la parte vendedora o arrendadora al cerrar la operación. Todo se transparenta por escrito desde el inicio."),
    ("¿Qué gastos adicionales debo considerar al comprar?",
     "Además del precio, hay que presupuestar entre 6 y 8 por ciento adicional: Impuesto sobre Adquisición de Inmuebles, honorarios notariales, avalúo, certificados y, si hay crédito, gastos de originación y seguros."),
    ("¿Puedo comprar si soy extranjero?",
     "Sí. En la Ciudad de México una persona extranjera puede adquirir directamente, sin necesidad de fideicomiso, cumpliendo con los requisitos migratorios y fiscales correspondientes. Te acompaño en ese proceso."),
    ("¿Cuánto tiempo toma vender una propiedad en CDMX?",
     "Con precio correcto y material profesional, el promedio en las colonias céntricas está entre seis y doce semanas. Las propiedades sobrevaloradas pueden pasar más de un año en el mercado."),
    ("¿Las propiedades del sitio son reales?",
     "Este sitio se encuentra en fase de demostración y el inventario mostrado es un conjunto de datos de ejemplo, claramente identificado como DEMO. El inventario real se publica conforme se integra a la plataforma."),
]

BLOG = [
    dict(slug="cuanto-cuesta-vivir-en-polanco", categoria="Zonas de CDMX",
         titulo="¿Cuánto cuesta vivir en Polanco en 2026?",
         resumen="El precio del departamento es solo una parte. Mantenimiento, predial, estacionamiento y estilo de vida cambian el número final más de lo que la gente espera.",
         lectura=7, fecha="2026-07-28",
         cuerpo=[
             ("El precio de entrada", "Un departamento de dos recámaras en Polanco en buen estado parte de alrededor de 9 millones de pesos y llega con facilidad a 18 millones en las secciones más demandadas. El precio por metro cuadrado promedio se ubica cerca de los 92,000 pesos, el más alto de la Ciudad de México junto con Lomas de Chapultepec.\n\nEn renta, dos recámaras amuebladas van de 45,000 a 75,000 pesos mensuales, y las opciones de tres recámaras con amenidades completas superan con frecuencia los 90,000."),
             ("Lo que casi nadie calcula", "El mantenimiento en Polanco es alto y no es negociable. En edificios con conserjería, gimnasio y salón de eventos, el rango va de 45 a 70 pesos por metro cuadrado al mes. Para un departamento de 180 m², eso significa entre 8,000 y 12,500 pesos mensuales solo de cuota condominal.\n\nEl predial de una propiedad de 12 millones ronda los 30,000 a 45,000 pesos anuales. Y el estacionamiento para visitas frecuentes es una fricción real: en buena parte de Polanco el estacionamiento en vía pública es de pago y limitado."),
             ("El costo del estilo de vida", "Vivir en Polanco implica tener a mano una oferta gastronómica y comercial de precio elevado. No es un gasto obligatorio, pero en la práctica el consumo cotidiano —café, supermercado, gimnasio, servicios— tiende a ser entre 20 y 35 por ciento más caro que en Del Valle o Narvarte.\n\nA cambio, se gana algo difícil de cuantificar: la posibilidad de resolver la vida diaria caminando, en una ciudad donde eso es la excepción."),
             ("¿Para quién tiene sentido?", "Polanco funciona muy bien para quien trabaja en el corredor Reforma-Polanco-Santa Fe y valora reducir traslados, para familias que priorizan cercanía a colegios y a Chapultepec, y para inversión de renta corporativa con inquilinos de estancia media.\n\nNo tiene sentido si la prioridad es maximizar metros cuadrados por peso invertido. En ese caso, Del Valle, Nápoles o Anzures ofrecen entre 30 y 45 por ciento más superficie por el mismo presupuesto."),
         ]),
    dict(slug="roma-norte-vs-condesa", categoria="Zonas de CDMX",
         titulo="Roma Norte vs Condesa: ¿dónde conviene vivir?",
         resumen="Son vecinas, comparten precio y se confunden todo el tiempo. Pero se viven distinto, y esa diferencia decide la compra.",
         lectura=6, fecha="2026-07-11",
         cuerpo=[
             ("La diferencia de fondo", "Roma Norte es una colonia porfiriana de traza ortogonal, con casonas de principios del siglo XX convertidas en galerías, oficinas creativas y restaurantes. Condesa es de los años veinte y treinta, con arquitectura art déco y funcionalista, camellones arbolados y un trazado más orgánico alrededor del antiguo hipódromo.\n\nRoma se siente urbana y activa. Condesa se siente residencial y verde. Ambas son caminables, pero Condesa lo es de una manera más tranquila."),
             ("Precio", "El precio por metro cuadrado es sorprendentemente similar: alrededor de 72,000 pesos en Roma Norte y 74,000 en Condesa. Hipódromo Condesa está ligeramente por encima, cerca de 78,000, por la calidad de su traza y la escasez de inventario.\n\nEn renta, ambas se mueven entre 320 y 345 pesos por metro cuadrado al mes. La diferencia real no está en el precio sino en el tipo de producto: Roma tiene más estudios y unidades de una recámara; Condesa tiene más departamentos de dos y tres recámaras con mejores proporciones."),
             ("Ruido y vida nocturna", "Este es el factor decisivo para muchos compradores. Roma Norte tiene mayor densidad de bares y restaurantes con operación nocturna, sobre todo en el cuadrante de Álvaro Obregón, Colima y Orizaba. Condesa concentra su vida nocturna en Nuevo León, Michoacán y Tamaulipas, dejando calles como Ámsterdam, Sonora y Cholula notablemente más tranquilas.\n\nSi la propiedad da a una de las calles activas, el ruido de fin de semana es real y constante. Vale la pena visitar cualquier departamento un viernes por la noche antes de decidir."),
             ("Estado de los edificios", "Ambas colonias tienen inventario antiguo que requiere revisión estructural cuidadosa, especialmente después de 2017. En Roma Norte hay más edificios con reforzamiento reciente documentado. En Condesa hay más construcciones catalogadas, lo que da carácter pero limita las intervenciones posibles.\n\nEn las dos zonas es indispensable pedir el dictamen estructural y revisar el estado del fondo de reserva del condominio antes de ofertar."),
             ("Entonces, ¿cuál?", "Roma Norte si buscas inversión de renta con máxima liquidez, vida urbana activa y no te molesta el movimiento constante. Condesa e Hipódromo si buscas vivir con más calma, tener parque a la puerta y valoras las proporciones de los departamentos antiguos.\n\nY si el presupuesto está ajustado, Roma Sur ofrece prácticamente los mismos servicios entre 15 y 25 por ciento más barato."),
         ]),
    dict(slug="errores-al-comprar-departamento-cdmx", categoria="Comprar",
         titulo="5 errores al comprar un departamento en CDMX",
         resumen="Los cinco que veo con más frecuencia, y que casi siempre se pueden evitar con una revisión de treinta minutos.",
         lectura=8, fecha="2026-06-24",
         cuerpo=[
             ("1. No presupuestar los gastos de cierre", "Es el error más común y el más caro. Muchos compradores calculan enganche y mensualidad, pero no los gastos de cierre: Impuesto sobre Adquisición de Inmuebles, honorarios notariales, avalúo, certificados de libertad de gravamen y, si hay crédito, gastos de originación y seguros.\n\nEn conjunto representan entre 6 y 8 por ciento del valor de la operación. En una compra de 8 millones, eso son entre 480,000 y 640,000 pesos que aparecen al final del proceso. He visto operaciones caerse a dos semanas de la firma por esto."),
             ("2. Ignorar el estado del condominio", "Comprar un departamento es comprar una parte de un edificio. Antes de ofertar hay que pedir el acta de la última asamblea, el estado del fondo de reserva y el historial de cuotas extraordinarias.\n\nUn edificio con fondo de reserva agotado y fachada pendiente de intervención te va a generar una cuota extraordinaria en los primeros dos años. Puede ser de 80,000 a 300,000 pesos, dependiendo del tamaño del edificio."),
             ("3. No revisar la estructura en edificios antiguos", "En Roma, Condesa, Juárez, Del Valle y Narvarte hay inventario de gran calidad arquitectónica con más de 60 años de antigüedad. Muchos de esos edificios están perfectamente sanos; otros tienen daños no visibles.\n\nUn dictamen estructural realizado por un Director Responsable de Obra cuesta entre 15,000 y 35,000 pesos. Comparado con el valor de la operación, es la revisión con mejor relación costo-beneficio que existe."),
             ("4. Comprar por el departamento y no por la calle", "El departamento se puede remodelar. La calle no. Ruido de bares, escuela con salida a la misma cuadra, avenida de alto tráfico, obra en construcción del lado de la ventana principal: todo eso es permanente y afecta tanto tu vida diaria como la reventa.\n\nMi recomendación es siempre la misma: visita la propiedad en tres momentos distintos. Un martes a las 8 de la mañana, un miércoles a las 7 de la tarde y un sábado por la noche."),
             ("5. Confundir precio de lista con valor de mercado", "Los precios publicados en portales son aspiraciones, no operaciones cerradas. En la Ciudad de México, la diferencia entre precio de lista y precio de cierre se ha movido históricamente entre 5 y 12 por ciento, dependiendo de la zona y del tiempo que la propiedad lleve publicada.\n\nAntes de ofertar hay que analizar operaciones efectivamente cerradas en la misma colonia y con características comparables. Ese análisis es la diferencia entre pagar el precio correcto y pagar el que alguien pidió."),
         ]),
    dict(slug="calcular-precio-por-metro-cuadrado", categoria="Comprar",
         titulo="Cómo calcular el precio por metro cuadrado (y por qué a veces engaña)",
         resumen="Es el indicador más usado del mercado inmobiliario y también el peor interpretado. Así se usa bien.",
         lectura=5, fecha="2026-06-09",
         cuerpo=[
             ("La fórmula, y su trampa", "El cálculo es simple: precio total dividido entre metros cuadrados de construcción. Un departamento de 9,000,000 de pesos con 120 m² da 75,000 pesos por metro cuadrado.\n\nEl problema empieza en el denominador. No todos los anuncios miden lo mismo. Algunos incluyen terraza y balcón al cien por ciento, otros al cincuenta, otros los excluyen. Algunos suman el cajón de estacionamiento y la bodega dentro de la superficie. La misma propiedad puede aparecer con 120, 138 o 152 m² dependiendo de quién la mida."),
             ("Qué debe incluirse", "El criterio más usado por valuadores en México considera superficie construida cubierta al cien por ciento, terrazas y balcones descubiertos al cincuenta por ciento, y estacionamiento y bodega valuados por separado, no sumados a la superficie habitable.\n\nAntes de comparar dos propiedades, verifica que ambas estén medidas con el mismo criterio. Lo más confiable es pedir el plano arquitectónico o el desglose de la escritura."),
             ("Lo que el indicador no ve", "El precio por metro cuadrado no distingue entre un departamento en planta baja frente a un ducto y un penthouse con terraza y vista abierta. Tampoco captura orientación, nivel, estado de conservación, calidad de acabados ni la salud financiera del condominio.\n\nEn edificios con amenidades, parte del valor está en áreas comunes que no aparecen en la superficie privativa. Un edificio con alberca, gimnasio y salón de eventos justifica un precio por metro cuadrado mayor que uno sin amenidades, con la misma ubicación."),
             ("Cómo usarlo bien", "El precio por metro cuadrado sirve para comparar propiedades similares en la misma colonia, no para comparar colonias distintas ni tipologías distintas.\n\nMi recomendación práctica: junta al menos seis operaciones cerradas en los últimos doce meses, en la misma colonia, con el mismo tipo de producto y un rango de superficie de más o menos 20 por ciento. Ese promedio sí te dice algo. Un solo dato aislado, no."),
         ]),
    dict(slug="credito-hipotecario-cdmx-guia", categoria="Créditos hipotecarios",
         titulo="Crédito hipotecario en CDMX: lo que conviene saber antes de solicitarlo",
         resumen="Enganche, capacidad de pago, tasa fija y los cuatro documentos que deciden si te autorizan.",
         lectura=7, fecha="2026-05-19",
         cuerpo=[
             ("Cuánto necesitas de enganche", "La mayoría de los bancos en México financian hasta el 80 o 85 por ciento del valor de avalúo para vivienda, lo que implica un enganche mínimo de 15 a 20 por ciento. Para segunda vivienda o inversión, el financiamiento suele bajar al 70 por ciento.\n\nUn punto importante: el banco presta sobre el valor de avalúo, no sobre el precio de compra. Si el avalúo sale por debajo del precio acordado, la diferencia la cubres tú en efectivo."),
             ("Capacidad de pago", "La regla que usan casi todas las instituciones es que la mensualidad del crédito no debe superar entre el 30 y el 35 por ciento de tu ingreso comprobable neto. Si tienes otros créditos vigentes —automotriz, tarjetas, personales—, esos pagos se descuentan de tu capacidad antes del cálculo.\n\nAntes de buscar propiedades, vale la pena pedir una precalificación. Es gratuita, no afecta tu historial y te da un rango real de presupuesto en lugar de uno imaginado."),
             ("Tasa fija y el CAT", "En México, prácticamente toda la oferta hipotecaria es de tasa fija en pesos por el plazo completo, lo cual es una ventaja frente a otros mercados. Lo que cambia entre bancos es la tasa, las comisiones y los seguros obligatorios.\n\nCompara siempre el Costo Anual Total y no solo la tasa. Dos créditos con la misma tasa nominal pueden tener un CAT distinto por comisión de apertura, seguro de vida y seguro de daños."),
             ("Los documentos que deciden", "Cuatro cosas pesan más que el resto: historial crediticio en Buró, antigüedad laboral o comprobación de ingresos si eres independiente, relación deuda-ingreso, y el avalúo de la propiedad.\n\nSi eres independiente o facturas, prepara al menos dos años de declaraciones anuales y doce meses de estados de cuenta. Es el escenario que más se atora y el que más tiempo requiere de preparación previa."),
             ("Cofinanciamiento", "Si cotizas al Infonavit o al Fovissste, existen esquemas de cofinanciamiento que suman tu subcuenta de vivienda al crédito bancario. Para propiedades en el rango de 2.5 a 6 millones puede mejorar sustancialmente las condiciones.\n\nVale la pena revisarlo aunque tu ingreso te permita un crédito bancario tradicional: en muchos casos reduce el enganche necesario."),
         ]),
    dict(slug="invertir-renta-cdmx-donde", categoria="Invertir",
         titulo="Dónde invertir para renta en CDMX: cuatro zonas con números",
         resumen="Rendimiento bruto, vacancia y perfil de inquilino en Roma Sur, Narvarte, Mixcoac y Escandón.",
         lectura=6, fecha="2026-04-30",
         cuerpo=[
             ("Cómo leer un rendimiento", "El rendimiento bruto anual se calcula dividiendo la renta anual entre el precio de compra. Es útil para comparar rápido, pero no es lo que te queda.\n\nEl rendimiento neto descuenta mantenimiento, predial, seguro, vacancia estimada y, si aplica, administración. En la Ciudad de México, la diferencia entre bruto y neto suele estar entre 1.2 y 1.8 puntos porcentuales. Un bruto de 6 por ciento se convierte con frecuencia en un neto de 4.3 a 4.8."),
             ("Roma Sur", "Precio por metro cuadrado cercano a 61,000 pesos y renta promedio alrededor de 275 pesos por metro al mes. Eso proyecta un bruto cercano al 5.4 por ciento.\n\nSu ventaja es la liquidez: comparte servicios con Roma Norte a menor costo de entrada. El perfil de inquilino es de profesionales de 28 a 40 años, con estancias de dos a cuatro años. La vacancia histórica es baja."),
             ("Narvarte", "Alrededor de 54,000 pesos por metro cuadrado en venta y 225 en renta mensual, para un bruto aproximado de 5 por ciento. El inventario de tres recámaras a buen precio la hace atractiva para familias, que tienden a permanecer más tiempo.\n\nMenor rotación significa menos costos de colocación y menos vacancia, aunque también menor flexibilidad para ajustar renta al alza."),
             ("Insurgentes Mixcoac", "Cerca de 58,000 pesos por metro en venta y 245 en renta, con un bruto aproximado del 5.1 por ciento. Su gran activo es la conectividad: cruce de dos líneas de Metro y Metrobús.\n\nLa demanda universitaria mantiene ocupación alta durante todo el año, con una rotación más frecuente. Es una zona que funciona bien para estudios y unidades de una recámara."),
             ("Escandón", "Alrededor de 56,000 pesos por metro y 240 de renta, para un bruto de 5.1 por ciento. Es la que tiene el componente de plusvalía más interesante de las cuatro: la obra nueva de los últimos años ha empujado el precio de manera sostenida.\n\nSi el objetivo combina flujo con apreciación de mediano plazo, es la zona que más recomiendo revisar hoy en el poniente."),
             ("Una advertencia", "Estos números son promedios de zona y sirven para orientar, no para decidir. El rendimiento real depende de la propiedad específica, del nivel, la orientación, el estado del condominio y el precio efectivamente negociado.\n\nAntes de comprar cualquier propiedad de inversión, hay que correr los números de esa propiedad en particular con comparables reales de renta de los últimos doce meses."),
         ]),
    dict(slug="vender-departamento-cdmx-precio", categoria="Vender",
         titulo="Por qué tu departamento no se vende (y casi nunca es la propiedad)",
         resumen="Las tres razones reales por las que una propiedad lleva ocho meses publicada en la Ciudad de México.",
         lectura=5, fecha="2026-04-08",
         cuerpo=[
             ("El precio de salida", "En ocho de cada diez casos que reviso, el problema es el precio inicial. Una propiedad sobrevalorada recibe visitas durante las primeras tres semanas y después el flujo se detiene por completo.\n\nPeor aún: el mercado aprende. Cuando una propiedad lleva seis meses publicada, los compradores asumen que algo tiene y empiezan a ofertar por debajo de su valor real. Bajar el precio después de ese punto rara vez recupera el interés inicial."),
             ("La primera fotografía", "La decisión de agendar una visita se toma en menos de tres segundos, mirando una imagen en un teléfono. Fotografías tomadas con celular, con poca luz, con la cama sin hacer o con muebles de más eliminan la propiedad antes de que alguien lea la descripción.\n\nUna sesión fotográfica profesional cuesta entre 3,500 y 8,000 pesos. En una propiedad de 8 millones es 0.06 por ciento del valor, y es la inversión con mejor retorno de todo el proceso de venta."),
             ("La descripción genérica", "Frases como 'excelente ubicación' o 'amplio y luminoso' no dicen nada porque las usa todo el mundo. Un comprador quiere saber a qué distancia está el Metro, si acepta mascotas, cuánto es el mantenimiento, qué orientación tiene y si el edificio tiene fondo de reserva.\n\nLa información concreta filtra mejor. Recibes menos solicitudes, pero de gente que ya sabe lo que va a encontrar y llega realmente interesada."),
             ("Qué hacer si ya llevas meses publicado", "Retira la publicación durante tres o cuatro semanas. Prepara la propiedad, toma material nuevo, ajusta el precio con base en comparables cerrados y vuelve a salir como un anuncio distinto.\n\nRelanzar bien funciona mucho mejor que ir bajando el precio en pequeños escalones frente a un mercado que ya te vio."),
         ]),
    dict(slug="rentar-cdmx-requisitos-2026", categoria="Rentar",
         titulo="Rentar en CDMX: requisitos, depósitos y qué revisar en el contrato",
         resumen="Aval, póliza jurídica, depósito e inventario. Lo que conviene tener listo antes de empezar a buscar.",
         lectura=6, fecha="2026-03-21",
         cuerpo=[
             ("Aval o póliza jurídica", "En la Ciudad de México, casi todos los arrendadores piden una de dos garantías: un aval con propiedad en la ciudad libre de gravamen, o una póliza jurídica contratada con una empresa especializada.\n\nLa póliza cuesta típicamente entre el 30 y el 50 por ciento de un mes de renta y la paga el inquilino. Es la opción más práctica si no tienes un aval disponible, y muchos arrendadores hoy la prefieren."),
             ("Documentos que te van a pedir", "Identificación oficial vigente, comprobante de domicilio actual, y comprobación de ingresos por al menos tres meses. Los arrendadores suelen requerir que el ingreso mensual comprobable sea de tres veces el monto de la renta.\n\nSi eres independiente, prepara estados de cuenta bancarios de seis a doce meses y, si facturas, tu constancia de situación fiscal. Tener el expediente completo antes de buscar puede ser la diferencia entre quedarte con la propiedad o perderla."),
             ("Depósito y pagos iniciales", "Lo habitual es un mes de depósito en garantía más el primer mes de renta por adelantado. Algunos arrendadores piden dos meses de depósito, sobre todo si hay mascotas o si el inmueble se entrega amueblado.\n\nEl depósito se devuelve al término del contrato, descontando daños que excedan el desgaste normal. Por eso el inventario inicial es tan importante."),
             ("El inventario, tu mejor protección", "Antes de firmar, documenta con fotografías y video el estado de cada espacio: pisos, muros, cocina, baños, ventanas, línea blanca y cualquier detalle preexistente. Anexa ese material al contrato firmado por ambas partes.\n\nEs el mecanismo más eficaz para evitar discusiones sobre el depósito al momento de la salida."),
             ("Cláusulas que conviene revisar", "Cuatro puntos concretos: el porcentaje de incremento anual y su referencia, quién cubre el mantenimiento ordinario y quién las reparaciones mayores, las condiciones para terminación anticipada y sus penalizaciones, y si se permiten mascotas por escrito.\n\nUn acuerdo verbal sobre mascotas no sirve de nada si el contrato dice lo contrario. Todo lo importante tiene que estar en el documento."),
         ]),
    dict(slug="vivir-en-del-valle-guia", categoria="Lifestyle",
         titulo="Vivir en Del Valle: la colonia que casi siempre gana la comparación",
         resumen="Por qué tantos compradores terminan en Del Valle después de recorrer media ciudad.",
         lectura=5, fecha="2026-02-27",
         cuerpo=[
             ("Tres secciones, tres colonias", "Del Valle es grande y conviene distinguirla. Del Valle Centro es la más consolidada, con los mejores servicios y el precio más alto. Del Valle Norte se acerca a Nápoles y a la vida de Insurgentes, con más obra nueva. Del Valle Sur es la más tranquila y con mejor relación precio-superficie.\n\nDecir 'quiero Del Valle' sin especificar sección deja fuera diferencias de precio de hasta 20 por ciento."),
             ("Lo que resuelve", "Escuelas, hospitales, mercados públicos, parques, Metro y Metrobús, todo dentro de la misma colonia. Es de las pocas zonas de la ciudad donde una familia puede resolver la vida cotidiana sin depender del auto todos los días.\n\nEl Parque Tlacoquemécatl, el Parque Hundido y el Parque de los Venados forman un triángulo de espacio público que pocas colonias igualan."),
             ("El producto típico", "Departamentos de 100 a 180 m² en edificios de 4 a 12 niveles, con dos cajones de estacionamiento y cuarto de servicio. Es una tipología pensada para familias y prácticamente no existe con estas proporciones en Roma o Condesa.\n\nTambién quedan casas de los años cincuenta en calles interiores, muchas con potencial de remodelación."),
             ("La plusvalía", "Del Valle no da saltos espectaculares de precio. Lo que da es constancia: ha crecido de manera sostenida durante décadas, sin las caídas que han tenido zonas más especulativas.\n\nPara una compra de largo plazo, esa previsibilidad vale más que un pico de apreciación que puede no repetirse."),
         ]),
    dict(slug="tendencias-mercado-cdmx-2026", categoria="Tendencias",
         titulo="Tres cosas que están cambiando en el mercado inmobiliario de CDMX",
         resumen="Verticalización del centro-sur, el peso del home office en la búsqueda y la nueva competencia por el inventario de renta.",
         lectura=6, fecha="2026-01-30",
         cuerpo=[
             ("La verticalización del centro-sur", "Benito Juárez y las zonas de Escandón, Mixcoac y Nápoles concentran hoy buena parte de la obra nueva vertical de escala media de la ciudad. Son edificios de 6 a 15 niveles, con 18 a 60 unidades, amenidades acotadas y unidades de 60 a 110 m².\n\nEs un producto distinto al de la década pasada: menos torres de gran altura y más edificios de escala barrial. Para el comprador significa más opciones de obra nueva fuera de Polanco y Santa Fe."),
             ("El home office dejó de ser un extra", "Hace cinco años el estudio era un plus. Hoy es un criterio de descarte. En las búsquedas que acompaño, la existencia de un espacio de trabajo con ventana propia decide más compras que la cercanía a un centro comercial.\n\nLos desarrolladores lo entendieron: la obra nueva de los últimos dos años en el centro-sur incluye con frecuencia un estudio o un área flexible incluso en unidades de dos recámaras."),
             ("Competencia por el inventario de renta", "En Roma, Condesa, Juárez y Del Valle, el inventario de renta larga compite con la renta de estancia media y corta. Eso ha reducido la oferta disponible para contratos anuales y ha empujado los precios al alza.\n\nPara el inquilino significa que hay que llegar con el expediente completo y decidir rápido. Para el inversionista, significa que la vacancia en esas zonas está en mínimos históricos, pero también que la regulación de la renta corta es un factor a vigilar."),
             ("Lo que no ha cambiado", "La ubicación exacta sigue decidiendo más que cualquier otra variable. Dos departamentos idénticos separados por cuatro cuadras pueden tener 20 por ciento de diferencia de valor y una velocidad de venta completamente distinta.\n\nEso no lo cambia ninguna tendencia."),
         ]),
]

BLOG_CATEGORIAS = ["Comprar", "Rentar", "Invertir", "Vender", "Créditos hipotecarios", "Zonas de CDMX", "Lifestyle", "Tendencias"]
